# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20171113_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_password',
        ),
    ]
