# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 18:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20171113_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
