# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_auto_20171114_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
    ]
